name: app-build-action-release
# æ¨é€ Tag æ—¶è§¦å‘
on:
  workflow_dispatch: # å…è®¸æ‰‹åŠ¨è§¦å‘
  push:
    tags:
      - "v*"
jobs:
  build-macos:
    runs-on: macos-latest
    permissions: write-all

    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4

      # è®¾ç½® Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: simple_live_app/pubspec.yaml
          cache: true

      # æ‰“å¼€ MAC Desktop æ”¯æŒ
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # æ›´æ–° Flutter çš„ packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # å®‰è£… appdmg npm install -g appdmg
      - name: Install appdmg
        run: npm install -g appdmg

      # è®¾ç½® Fastforge ç¯å¢ƒ
      - name: Install fast-forge
        run: |
          git clone https://github.com/SlotSun/fastforge.git
          cd fastforge
          dart pub global activate melos
          melos run activate

      # æ‰“åŒ… MAC
      - name: Build MacOS
        run: |
          cd simple_live_app
          fastforge package --platform macos --targets dmg --skip-clean

      # ä¸Šä¼  MAC è‡³ Artifacts
      - name: Upload MacOS to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: |
            simple_live_app/build/dist/*/*.dmg

      # è¯»å–ç‰ˆæœ¬ä¿¡æ¯
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/app_version.json
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"

      # ä¸Šä¼ è‡³ Release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ fromJson(steps.version.outputs.content).version }}"
          body: "${{ fromJson(steps.version.outputs.content).version_desc }}"
          prerelease: ${{ fromJson(steps.version.outputs.content).prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ fromJson(steps.version.outputs.content).version }}
          files: |
            simple_live_app/build/dist/*/*.dmg
      # å®Œæˆ
      - run: echo "ğŸ This job's status is ${{ job.status }}."
